// api/src/modules/sports-feed/country-iso.ts
// Maps API-Football's English country names to the ISO 3166-1 alpha-3 codes the
// Altenar feed tags each category with, so we can compare "which country" on a
// language-independent key. Unknown names return null → no country constraint
// (the match falls back to name-only behaviour).

const NAME_TO_ISO3: Record<string, string> = {
  brazil: 'BRA',
  usa: 'USA',
  'united states': 'USA',
  england: 'ENG',
  scotland: 'SCO',
  wales: 'WAL',
  'northern ireland': 'NIR',
  ireland: 'IRL',
  spain: 'ESP',
  italy: 'ITA',
  germany: 'DEU',
  france: 'FRA',
  portugal: 'PRT',
  netherlands: 'NLD',
  belgium: 'BEL',
  argentina: 'ARG',
  uruguay: 'URY',
  paraguay: 'PRY',
  chile: 'CHL',
  colombia: 'COL',
  peru: 'PER',
  ecuador: 'ECU',
  bolivia: 'BOL',
  venezuela: 'VEN',
  mexico: 'MEX',
  canada: 'CAN',
  sweden: 'SWE',
  norway: 'NOR',
  denmark: 'DNK',
  finland: 'FIN',
  iceland: 'ISL',
  'faroe islands': 'FRO',
  estonia: 'EST',
  latvia: 'LVA',
  lithuania: 'LTU',
  poland: 'POL',
  'czech republic': 'CZE',
  czechia: 'CZE',
  slovakia: 'SVK',
  austria: 'AUT',
  switzerland: 'CHE',
  hungary: 'HUN',
  romania: 'ROU',
  bulgaria: 'BGR',
  serbia: 'SRB',
  croatia: 'HRV',
  slovenia: 'SVN',
  greece: 'GRC',
  turkey: 'TUR',
  russia: 'RUS',
  ukraine: 'UKR',
  belarus: 'BLR',
  australia: 'AUS',
  'new zealand': 'NZL',
  japan: 'JPN',
  'south korea': 'KOR',
  'korea republic': 'KOR',
  china: 'CHN',
  'saudi arabia': 'SAU',
  qatar: 'QAT',
  'united arab emirates': 'ARE',
  lebanon: 'LBN',
  egypt: 'EGY',
  morocco: 'MAR',
  algeria: 'DZA',
  tunisia: 'TUN',
  nigeria: 'NGA',
  ghana: 'GHA',
  'south africa': 'ZAF',
  cameroon: 'CMR',
  'ivory coast': 'CIV',
  senegal: 'SEN',
  india: 'IND',
  indonesia: 'IDN',
};

/** English country name → ISO3, or null when unknown. */
export function countryToIso3(name?: string | null): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase().replace(/-/g, ' ').replace(/\s+/g, ' ');
  return NAME_TO_ISO3[key] ?? null;
}
